#workflow_call
name: Callable Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name for greeting'
        required: true
        type: 'string'
    outputs:
      greetingMessage:
        description: 'Generated greeting message'
        value: ${{ steps.greeting.outputs.message }}

jobs:
  generate-greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Greeting
        id: greeting
        run: echo "message=Hello, ${{ inputs.name }}!" >> $GITHUB_ENV
        env:
          GITHUB_ENV: ${{ github.env }}

    
      
