name: hello-world
run-name: run-name-test-hello-world

on: 
  push:
   branches:
    - main 
    - master 
jobs:
 hello:
  runs-on: ubuntu-latest
  steps:
   - name: hello world
     run: echo "hello world" 
 
