name: hello-world
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  push:
   branches:
    - main 
    - master 
jobs:
 hello:
  runs-on: ubuntu-latest
  steps:
   - name: hello world
     run: echo "hello world" 
