name: status check

on:
 workflow_dispatch:

jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello world1"
        shell: bash
